# Use a imagem Nginx como base
FROM nginx:alpine

# Copie os arquivos HTML, CSS, JavaScript e outros ativos estáticos para o diretório de trabalho no contêiner
COPY . /usr/share/nginx/html

# Exponha a porta 3000 para tráfego HTTP
EXPOSE 3000


