version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - database
    healthcheck:
      test: curl --fail http://database:5432/ || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: covid
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    